### PR TITLE
Add devpost link to project cards

### LINKED ISSUE #75: "Error: Neither validate nor simple validate defined on handler"
Server crashes after clicking "Populate Server" on populate page

### LINKED ISSUE #139: Add link to devpost on project card
right now we import the names of projects and table numbers from dev post and i think the summaries too, however for the online hackathon we may need a few extra things since the judges wont be in person. We definitely need to also add a link to see the project on devpost, since the hackers will be required to also put a demo video on devpost for judges to watch.

Other things may be interesting to add but this is the main thing I'm looking for.

### PR DESCRIPTION
**Pull request by samuel-ping**
I couldn't test a full judging run, because I was running into an error during the judging phase where it threw a "Can't find new assignment error"

### CODE REVIEW

**Comment by sahej172002** [comment]
@samuel-ping Have you tested your changes?

**Comment by samuel-ping** [comment]
@sahej172002 Yes, I think? It definitely works, and when I was testing it, I ran into an unrelated error (I'm pretty sure its unrelated) that I specified above. I think the error is related to the number of judges versus the number of projects (I had three judges judge 5 projects in my test), but I'm not sure what went wrong there tbh.

It also passed the test pipeline which hopefully means its fine.

**Review by sahej172002 — APPROVED** [review]

**Review by sahej172002 — APPROVED** [review]

**Review by mjrb — APPROVED** [review]
LGTM my only comment is that it seems like  the judging table creator script got included in here, Even though it was already merged in another PR. This is potentially because you may have needed to rebase over master after the script merged. Something to keep in mind for the future but this looks good to merge

**Comment by samuel-ping** [comment]
Oh what the heck you're right, hauhhhh I didn't even notice. Thanks for the tip!

**Pull request merged**
