### PR TITLE
Added schema for addRow and authenticate

### PR DESCRIPTION
**Pull request by chiayi**
Is this okay?

### CODE REVIEW

**Comment by three** [comment]
The schema looks good, but please keep formatting consistent (2 space indent) and fix the linting errors.

**Comment by three** [comment]
Can you be more consistent with formatting? It looks like there might have been some auto-indentation errors when you tried to fix it. Also, keep one space after but not before the colon when defining properties. For instance, `"type": "object"` instead of `"type" : "object"`.

**Comment by three** [comment]
After doing some testing you're schema for `AddRow` isn't quite valid.

An `AddRow` will look something like:

```json
{
  "table": "TABLE_JUDGE",
  "row": {
    "name": "Jon Doe",
    "email": "jon.doe@gmail.com",
    "active": 1
  },
  "returnId": "2c50c457c6fb"
}
```

You should put what you have under the `row` property, and then have the root of the schema be an object with `table` and `row`.

(edit: `AddRow`, not the response)

**Comment by chiayi** [comment]
Does the row property need to be an object itself so that it itself can have all the necessary properties or is what I added okay?

**Comment by three** [comment]
You can check your work with a tool like https://www.jsonschemavalidator.net/. What you essentially want to do is,

```json
{
  "type": "object",
  "required": [ "table", "row" ],
  "properties": {
    "table": { "type": "string" },
    "row": {
      "anyOf": [ ... ]
    }
  }
}
```

where `anyOf` is what you were doing before. Also, double check formatting again.

**Comment by three** [comment]
Essentially what's attached to `"row"` is itself a schema.

**Pull request closed without merging**
